# Use OpenJDK base image (lightweight version)
FROM openjdk:17-jdk-slim

RUN apt-get update && apt-get install -y curl

# Set the working directory inside the container
WORKDIR /app

# Copy the built JAR file into the container
COPY target/config-server-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your Spring Boot app listens on
EXPOSE 8888

# Start the Spring Boot app
ENTRYPOINT ["java", "-jar", "app.jar"]